services:
  database:
    image: mysql:8
    ports:
      - "3307:3306"
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql_databases
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "learn-search"
